# Generated by Django 4.2.4 on 2023-08-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='reciperequirement',
            options={'ordering': ['menuItem']},
        ),
    ]
